name: "LaTex Build PDF"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: xu-cheng/latex-action@3.0.0
        with:
          root_file: main.tex
          working_directory: ../
      - name: upload
        uses: actions/upload-artifact@v4.3.4
        with:
          name: PDF
          path: main.pdf
        
